### ISSUE TITLE
Updater - Report on and add a way to update secondary (non-Direct) composer dependencies

### ISSUE THREAD

**Issue by CoderBrandon** [waffle-ops/waffle#101]
Currently `update-status` and `update-apply` only looks at direct (`-D`) composer dependencies. There can be cases where there are pending non-direct dependencies that should be updated as well.

We should make two changes, minimally:
1. In `update-status`, it should build a second table for minor updates for non-direct dependencies
2. In `update-apply`, it should have a way of updating non-direct dependencies (we would need to build a way of determining which direct dependency is requiring the secondary dependency and then update `--with-all-dependencies` or something similar)

In addition, if possible, we should look into a way of doing something similar to `drush pm-updatestatus` before it was deprecated. Possibly as a drush command in a contrib module like https://www.drupal.org/project/vitals . The goal being to show a similar output that you can see on the update status page in the Drupal admin. Also something like `drush eval "var_export(update_get_available(TRUE));"`

**Comment by daceej** [comment]
Existing code for this was pushed with v0.0.5-alpha.
