### ISSUE TITLE
composer outdated thinks "No pending updates detected"

### ISSUE THREAD

**Issue by earthday47** [waffle-ops/waffle#41]
Running `feature/updates` branch. Running `wfl site:update:apply` on a Drupal 8 site, all basic configs, triggered the "No pending updates detected" error in UpdateApply.php ~L423. Inspecting the `$pending_updates` variable, "installed" definitely exists and is populated.
Commenting out the if (empty) check allows the command to proceed.

Not sure what's different about my system. I'm running PHP 7.3 on my host.

**Comment by CoderBrandon** [comment]
I think this is resolved now in `1.x` - reopen or comment if you still run into it.
