### ISSUE TITLE
Remove site:sync command + Define Recipe API.

### ISSUE THREAD

**Issue by daceej** [waffle-ops/waffle#56]
Waffle is supposed to be the liaison between site configuration / setup / maintenance and development. 

`Tasks` - A single unit of work (ie. syncing the database, syncing the files, running a release script, etc...)
`Recipes` - A collection of `Tasks`. Can provide each task with input arguments.
`Commands` - These are traditional Symfony CLI comands (ie `list`, `help`). I think `iterate` falls into this category. `Commands` are _always_ available (even outside a project directory). 

Waffle aims to provide tasks out of the box that are 'sensible'. We are targeting Drupal and WordPress sites hosted on Acquia or Pantheon. The provided tasks are geared towards those types of configuration, but every project is different. The task system allows users to re-define the provided tasks if there is a project that needs to vary slightly. 

Waffle needs to define some sort of API around recipes. Projects are meant to define recipes with predefined tasks that are provided. The predefined tasks can be overridden in the project config if they are too opinionated for the project (ie site:sync:db needs to pull 2 databases instead of 1, so it is overridden to use a shell script instead). 

Waffle can provide some recipes. Most D7 sites on Acquia for example are going to be the same. A `local:setup` recipe would be largely the same. Again, individual tasks could still be overridden if a single step needs to work differently. If the project has many variations, a complete override of a `local:setup` recipe maybe a better fit.

The goal of this issue is to lay out what the minimum `Recipes` that waffle should expect to have defined per-project / include as a sensible default.

Tasks/Recipes that waffle expects every project to provide (WIP):
(Task) `scaffold` / `project:init` - Used to guide the user in setting up a project to work with waffle
(Task) `audit` - Checks things 
TBD

Considerations:
(Recipe) `project:setup` - Performs initial install?
(Recipe) `project:deploy` -- constructs a build artifact and pushes it somewhere?

Another effort will be made to draw the line between tasks and recipes (https://github.com/waffle-ops/waffle/issues/55).

**Comment by CoderBrandon** [comment]
I think a `project:release` recipe default would be helpful. It would do common release things like clearing cache, updating database, etc. There would be a slight overlap with `project:deploy` - maybe it would even be a subset of that somehow.

**Comment by daceej** [comment]
Calling this done - https://github.com/waffle-ops/waffle/wiki/Overview

We can re-open or make a new issue to track what tasks and recipes should be provided and how their defaults should work.
